### ISSUE TITLE
Add docker-compose.yml to start development environment

### ISSUE THREAD

**Issue by hugochinchilla** [the-destro/amhappy#4]
I'm having trouble to get it to start, it would be great to have a docker-compose.yml file and just make docker-compose up to get it started.

```
Traceback (most recent call last):
  File "/home/hchinchilla/.virtualenvs/amhappy/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.5.4', 'console_scripts', 'pserve')()
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/pkg_resources.py", line 742, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/hchinchilla/.virtualenvs/amhappy/local/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: backports.ssl-match-hostname
```

**Comment by hugochinchilla** [comment]
Ok, figured it out, DistributionNotFound just means I have to install this package

**Comment by the-destro** [comment]
hopefully over the weekend I can polish this some more and get some examples up. I had to remove so company specific stuff.

**Comment by hugochinchilla** [comment]
It looks quite good, but I don't understand what is the /code mountpoint for, it's breaking things for me.
And another unrelated question, the dashboard is suposed to be served from another server or should be accesible trough the pyramid app?

**Comment by the-destro** [comment]
Should be accessible from the app. The /code mount point is a temporary thing specific to our docker setups. Basically it allowed for automating the creation of a code data container where all of the code checkouts would be. This then code be imported into the various applications.

**Comment by the-destro** [comment]
D'oh, just remembered that I need to automate installing the dashboard, i.e. running an npm install in its directory since it is an angular app.

**Comment by hugochinchilla** [comment]
I got it working, but needed to tweak some things, grunt serve was failing so I used the php development server to serve the files, also I had to move bower_components inside app to make it work.
